name: Python CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run tests
        run:
          python -m unittest test_suma.py
      - name: Run test 2  
        run:
          python -m unittest test_resta.py

